services:
  - type: web
    name: traccar
    env: java
    buildCommand: "./gradlew build"
    startCommand: "java -jar target/tracker-server.jar"
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
    autoDeploy: true
